language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vinaylogics/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vinaylogics/docker-react npm run test